# Generated by Django 5.0.2 on 2024-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='текст')),
                ('created_at', models.DateTimeField(verbose_name='дата публикации')),
                ('image', models.CharField(max_length=200, verbose_name='изображение')),
            ],
        ),
    ]
